railstutorial: "https://www.railstutorial.org/"
railstutorial_help: "https://www.railstutorial.org/help"
railstutorial_book: "https://www.railstutorial.org/book"
screencasts: "https://screencasts.railstutorial.org/"
contact_page: https://www.railstutorial.org/contact
learnenough: "https://www.learnenough.com/"
home_image_size: 200px
